# Import Statement

In [ ]:
import pandas as pd

# Data Cleaning

In [ ]:
raw_data = pd.read_csv("Absenteeism_data.csv")

,ID,Reason for Absence,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,11,26,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,36,0,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,3,23,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,7,7,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,11,23,23/07/2015,289,36,33,239.554,30,1,2,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...
695,17,10,23/05/2018,179,22,40,237.656,22,2,2,0,8
696,28,6,23/05/2018,225,26,28,237.656,24,1,1,2,3
697,18,10,24/05/2018,330,16,28,237.656,25,2,0,0,8
698,25,23,24/05/2018,235,16,32,237.656,25,3,0,0,2
699,15,28,31/05/2018,291,31,40,237.656,25,1,1,1,2

In [ ]:
data = raw_data.copy()

,ID,Reason for Absence,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,11,26,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,36,0,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,3,23,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,7,7,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,11,23,23/07/2015,289,36,33,239.554,30,1,2,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...
695,17,10,23/05/2018,179,22,40,237.656,22,2,2,0,8
696,28,6,23/05/2018,225,26,28,237.656,24,1,1,2,3
697,18,10,24/05/2018,330,16,28,237.656,25,2,0,0,8
698,25,23,24/05/2018,235,16,32,237.656,25,3,0,0,2
699,15,28,31/05/2018,291,31,40,237.656,25,1,1,1,2

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ID                         700 non-null    int64
 1   Reason for Absence         700 non-null    int64
 2   Date                       700 non-null    object
 3   Transportation Expense     700 non-null    int64
 4   Distance to Work           700 non-null    int64
 5   Age                        700 non-null    int64
 6   Daily Work Load Average    700 non-null    float64
 7   Body Mass Index            700 non-null    int64
 8   Education                  700 non-null    int64
 9   Children                   700 non-null    int64
 10  Pets                       700 non-null    int64
 11  Absenteeism Time in Hours  700 non-null    int64
dtypes: float64(1), int64(10), object(1)
memory usage: 65.8+ KB

In [ ]:
data = data.drop(['ID'], axis = 1)

,Reason for Absence,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,26,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,0,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,23,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,7,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,23,23/07/2015,289,36,33,239.554,30,1,2,1,2
...,...,...,...,...,...,...,...,...,...,...,...
695,10,23/05/2018,179,22,40,237.656,22,2,2,0,8
696,6,23/05/2018,225,26,28,237.656,24,1,1,2,3
697,10,24/05/2018,330,16,28,237.656,25,2,0,0,8
698,23,24/05/2018,235,16,32,237.656,25,3,0,0,2
699,28,31/05/2018,291,31,40,237.656,25,1,1,1,2

# Data Preprocessing

### Modify the Reasons for absence column

The reason categories are health related and include:
- Reason_1: 1-14 = Diseases
- Reason_2: 15-17 = Pregnancy and childbirth
- Reason_3: 18-21 = Accidents and Poisonings
- Reason_4: 22-28 = Medical appointments

In [ ]:
data['Reason for Absence'].unique()

array([26,  0, 23,  7, 22, 19,  1, 11, 14, 21, 10, 13, 28, 18, 25, 24,  6,
       27, 17,  8, 12,  5,  9, 15,  4,  3,  2, 16])

In [ ]:
sorted(data['Reason for Absence'].unique())

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28]

In [ ]:
reason_columns = pd.get_dummies(data['Reason for Absence'], drop_first = True)

In [ ]:
reason_columns

,1,2,3,4,5,6,7,8,9,10,...,18,19,21,22,23,24,25,26,27,28
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
3,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
696,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
697,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
698,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
699,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True

In [ ]:
reason_cat_1 = reason_columns.loc[:, 1:14].max(axis=1)
reason_cat_2 = reason_columns.loc[:, 15:17].max(axis=1)
reason_cat_3 = reason_columns.loc[:, 18:21].max(axis=1)
reason_cat_4 = reason_columns.loc[:, 22:].max(axis=1)

In [ ]:
data = data.drop(['Reason for Absence'], axis = 1)

In [ ]:
data = pd.concat([data, reason_cat_1, reason_cat_2, reason_cat_3, reason_cat_4], axis = 1)
data

,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours,0,1,2,3
0,07/07/2015,289,36,33,239.554,30,1,2,1,4,False,False,False,True
1,14/07/2015,118,13,50,239.554,31,1,1,0,0,False,False,False,False
2,15/07/2015,179,51,38,239.554,31,1,0,0,2,False,False,False,True
3,16/07/2015,279,5,39,239.554,24,1,2,0,4,True,False,False,False
4,23/07/2015,289,36,33,239.554,30,1,2,1,2,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,23/05/2018,179,22,40,237.656,22,2,2,0,8,True,False,False,False
696,23/05/2018,225,26,28,237.656,24,1,1,2,3,True,False,False,False
697,24/05/2018,330,16,28,237.656,25,2,0,0,8,True,False,False,False
698,24/05/2018,235,16,32,237.656,25,3,0,0,2,False,False,False,True
699,31/05/2018,291,31,40,237.656,25,1,1,1,2,False,False,False,True

In [ ]:
data.columns.values

array(['Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 0, 1, 2, 3],
      dtype=object)

In [ ]:
column_names = ['Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 'Reason_1', 'Reason_2', 'Reason_3', 'Reason_4']

In [ ]:
data.columns = column_names

In [ ]:
data.head()

,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours,Reason_1,Reason_2,Reason_3,Reason_4
0,07/07/2015,289,36,33,239.554,30,1,2,1,4,False,False,False,True
1,14/07/2015,118,13,50,239.554,31,1,1,0,0,False,False,False,False
2,15/07/2015,179,51,38,239.554,31,1,0,0,2,False,False,False,True
3,16/07/2015,279,5,39,239.554,24,1,2,0,4,True,False,False,False
4,23/07/2015,289,36,33,239.554,30,1,2,1,2,False,False,False,True

In [ ]:
column_reorder = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4',
                          'Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours']

In [ ]:
data = data[column_reorder]

In [ ]:
data.head()

,Reason_1,Reason_2,Reason_3,Reason_4,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,False,False,False,True,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,False,False,False,False,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,False,False,False,True,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,True,False,False,False,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,False,False,False,True,23/07/2015,289,36,33,239.554,30,1,2,1,2

In [ ]:
# @title Checkpoint
data_reason_mod = data.copy()

### Modify the Date column

In [ ]:
type(data_reason_mod['Date'][0])

str

In [ ]:
data_reason_mod['Date'] = pd.to_datetime(data_reason_mod['Date'], format = '%d/%m/%Y')

In [ ]:
data_reason_mod.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Reason_1                   700 non-null    bool
 1   Reason_2                   700 non-null    bool
 2   Reason_3                   700 non-null    bool
 3   Reason_4                   700 non-null    bool
 4   Date                       700 non-null    datetime64[ns]
 5   Transportation Expense     700 non-null    int64
 6   Distance to Work           700 non-null    int64
 7   Age                        700 non-null    int64
 8   Daily Work Load Average    700 non-null    float64
 9   Body Mass Index            700 non-null    int64
 10  Education                  700 non-null    int64
 11  Children                   700 non-null    int64
 12  Pets                       700 non-null    int64
 13  Absenteeism Time in Hours  700 non-null    int64
dtypes: bool(4), datetime64[ns](1), float64(1), int64(8)
memory usage: 57.5 KB

#### Extract Month

In [ ]:
list_months = []

In [ ]:
for i in range(data_reason_mod.shape[0]):
    list_months.append(data_reason_mod['Date'][i].month)

In [ ]:
data_reason_mod['Month'] = list_months

In [ ]:
data_reason_mod.head(20)

,Reason_1,Reason_2,Reason_3,Reason_4,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours,Month
0,False,False,False,True,2015-07-07,289,36,33,239.554,30,1,2,1,4,7
1,False,False,False,False,2015-07-14,118,13,50,239.554,31,1,1,0,0,7
2,False,False,False,True,2015-07-15,179,51,38,239.554,31,1,0,0,2,7
3,True,False,False,False,2015-07-16,279,5,39,239.554,24,1,2,0,4,7
4,False,False,False,True,2015-07-23,289,36,33,239.554,30,1,2,1,2,7
5,False,False,False,True,2015-07-10,179,51,38,239.554,31,1,0,0,2,7
6,False,False,False,True,2015-07-17,361,52,28,239.554,27,1,1,4,8,7
7,False,False,False,True,2015-07-24,260,50,36,239.554,23,1,4,0,4,7
8,False,False,True,False,2015-07-06,155,12,34,239.554,25,1,2,0,40,7
9,False,False,False,True,2015-07-13,235,11,37,239.554,29,3,1,1,8,7
10,True,False,False,False,2015-07-20,260,50,36,239.554,23,1,4,0,8,7
11,True,False,False,False,2015-07-14,260,50,36,239.554,23,1,4,0,8,7
12,True,False,False,False,2015-07-15,260,50,36,239.554,23,1,4,0,8,7
13,True,False,False,False,2015-07-15,179,51,38,239.554,31,1,0,0,1,7
14,False,False,False,True,2015-07-15,179,51,38,239.554,31,1,0,0,4,7
15,True,False,False,False,2015-07-17,246,25,41,239.554,23,1,0,0,8,7
16,False,False,False,True,2015-07-17,179,51,38,239.554,31,1,0,0,2,7
17,False,False,True,False,2015-07-27,179,51,38,239.554,31,1,0,0,8,7
18,True,False,False,False,2015-07-30,189,29,33,239.554,25,1,2,2,8,7
19,False,False,False,True,2015-08-05,248,25,47,205.917,32,1,2,1,2,8

#### Extract Day

In [ ]:
def date_to_weekday(date_value):
    return date_value.weekday()

In [ ]:
data_reason_mod['Weekday'] = data_reason_mod['Date'].apply(date_to_weekday)

In [ ]:
data_reason_mod.head()

,Reason_1,Reason_2,Reason_3,Reason_4,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours,Month,Weekday
0,False,False,False,True,2015-07-07,289,36,33,239.554,30,1,2,1,4,7,1
1,False,False,False,False,2015-07-14,118,13,50,239.554,31,1,1,0,0,7,1
2,False,False,False,True,2015-07-15,179,51,38,239.554,31,1,0,0,2,7,2
3,True,False,False,False,2015-07-16,279,5,39,239.554,24,1,2,0,4,7,3
4,False,False,False,True,2015-07-23,289,36,33,239.554,30,1,2,1,2,7,3

In [ ]:
data_reason_mod = data_reason_mod.drop(['Date'], axis = 1)
data_reason_mod.head()

,Reason_1,Reason_2,Reason_3,Reason_4,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours,Month,Weekday
0,False,False,False,True,289,36,33,239.554,30,1,2,1,4,7,1
1,False,False,False,False,118,13,50,239.554,31,1,1,0,0,7,1
2,False,False,False,True,179,51,38,239.554,31,1,0,0,2,7,2
3,True,False,False,False,279,5,39,239.554,24,1,2,0,4,7,3
4,False,False,False,True,289,36,33,239.554,30,1,2,1,2,7,3

In [ ]:
new_column_names = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month', 'Weekday',
       'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education', 'Children',
       'Pets', 'Absenteeism Time in Hours']

In [ ]:
data_reason_mod = data_reason_mod[new_column_names]
data_reason_mod.head()

,Reason_1,Reason_2,Reason_3,Reason_4,Month,Weekday,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,False,False,False,True,7,1,289,36,33,239.554,30,1,2,1,4
1,False,False,False,False,7,1,118,13,50,239.554,31,1,1,0,0
2,False,False,False,True,7,2,179,51,38,239.554,31,1,0,0,2
3,True,False,False,False,7,3,279,5,39,239.554,24,1,2,0,4
4,False,False,False,True,7,3,289,36,33,239.554,30,1,2,1,2

In [ ]:
# @title Checkpoint 2
data_reason_date_mod = data_reason_mod.copy()
data_reason_date_mod

,Reason_1,Reason_2,Reason_3,Reason_4,Month,Weekday,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,False,False,False,True,7,1,289,36,33,239.554,30,1,2,1,4
1,False,False,False,False,7,1,118,13,50,239.554,31,1,1,0,0
2,False,False,False,True,7,2,179,51,38,239.554,31,1,0,0,2
3,True,False,False,False,7,3,279,5,39,239.554,24,1,2,0,4
4,False,False,False,True,7,3,289,36,33,239.554,30,1,2,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,True,False,False,False,5,2,179,22,40,237.656,22,2,2,0,8
696,True,False,False,False,5,2,225,26,28,237.656,24,1,1,2,3
697,True,False,False,False,5,3,330,16,28,237.656,25,2,0,0,8
698,False,False,False,True,5,3,235,16,32,237.656,25,3,0,0,2
699,False,False,False,True,5,3,291,31,40,237.656,25,1,1,1,2

### Modify the Education column

In [ ]:
data_reason_date_mod['Education'].value_counts()

Education
1    583
3     73
2     40
4      4
Name: count, dtype: int64

In [ ]:
data_reason_date_mod['Education'] = data_reason_date_mod['Education'].map({1:0, 2:1, 3:1, 4:1})

In [ ]:
data_reason_date_mod['Education'].value_counts()

Education
0    583
1    117
Name: count, dtype: int64

### Export *Data*

In [ ]:
# @title Checkpoint 3
df_preprocessed = data_reason_date_mod.copy()
df_preprocessed.head(10)
df_preprocessed.to_csv('Absenteeism_preprocessed.csv', index = False)